export const PERMISSIONS = [
  { key: 'dashboard.view', label: 'View Dashboard', module: 'Dashboard' },
  { key: 'kittens.view', label: 'View Kittens', module: 'Kittens' },
  { key: 'kittens.create', label: 'Create Kittens', module: 'Kittens' },
  { key: 'kittens.edit', label: 'Edit Kittens', module: 'Kittens' },
  { key: 'kittens.delete', label: 'Delete Kittens', module: 'Kittens' },
  { key: 'fosters.view', label: 'View Fosters', module: 'Fosters' },
  { key: 'fosters.manage', label: 'Manage Fosters', module: 'Fosters' },
  { key: 'litters.view', label: 'View Litters', module: 'Litters' },
  { key: 'litters.manage', label: 'Manage Litters', module: 'Litters' },
  { key: 'medical.view', label: 'View Medical Records', module: 'Medical' },
  { key: 'medical.manage', label: 'Manage Medical Records', module: 'Medical' },
  { key: 'documents.view', label: 'View Documents', module: 'Documents' },
  { key: 'documents.manage', label: 'Manage Documents', module: 'Documents' },
  { key: 'applications.view', label: 'View Applications', module: 'Applications' },
  { key: 'applications.manage', label: 'Manage Applications', module: 'Applications' },
  { key: 'content.view', label: 'View Website Content', module: 'Website' },
  { key: 'content.manage', label: 'Manage Website Content', module: 'Website' },
  { key: 'events.view', label: 'View Calendar Events', module: 'Calendar' },
  { key: 'events.manage', label: 'Manage Calendar Events', module: 'Calendar' },
  { key: 'donations.view', label: 'View Donations', module: 'Donations' },
  { key: 'donations.manage', label: 'Manage Donations', module: 'Donations' },
  { key: 'sponsorships.view', label: 'View Sponsorships', module: 'Sponsorships' },
  { key: 'sponsorships.manage', label: 'Manage Sponsorships', module: 'Sponsorships' },
  { key: 'reports.view', label: 'View Reports', module: 'Reports' },
  { key: 'users.view', label: 'View Users', module: 'Users & Roles' },
  { key: 'users.manage', label: 'Manage Users', module: 'Users & Roles' },
  { key: 'roles.manage', label: 'Manage Roles & Permissions', module: 'Users & Roles' },
  { key: 'settings.manage', label: 'Manage Organization Settings', module: 'Settings' },
  { key: 'emails.view', label: 'View Email Templates', module: 'Emails' },
  { key: 'emails.manage', label: 'Manage Email Templates & Delivery', module: 'Emails' },
];

export const PERMISSION_KEYS = PERMISSIONS.map((p) => p.key);

export const DEFAULT_ROLES = [
  {
    name: 'Super Admin',
    description: 'Full access to every module and setting.',
    isSystem: true,
    permissions: PERMISSION_KEYS,
  },
  {
    name: 'Admin',
    description: 'Day-to-day rescue operations without role management.',
    isSystem: true,
    permissions: PERMISSION_KEYS.filter((k) => k !== 'roles.manage'),
  },
  {
    name: 'Medical Staff',
    description: 'Medical records, documents, and kitten health data.',
    isSystem: true,
    permissions: [
      'dashboard.view',
      'kittens.view',
      'kittens.edit',
      'medical.view',
      'medical.manage',
      'documents.view',
      'documents.manage',
      'fosters.view',
      'litters.view',
    ],
  },
  {
    name: 'Foster Coordinator',
    description: 'Foster homes, placements, and adoption applications.',
    isSystem: true,
    permissions: [
      'dashboard.view',
      'kittens.view',
      'kittens.create',
      'kittens.edit',
      'fosters.view',
      'fosters.manage',
      'litters.view',
      'litters.manage',
      'applications.view',
      'applications.manage',
      'documents.view',
      'documents.manage',
      'events.view',
    ],
  },
  {
    name: 'Foster Parent',
    description: 'Portal access for assigned foster kittens only.',
    isSystem: true,
    permissions: [
      'dashboard.view',
      'kittens.view',
      'medical.view',
      'medical.manage',
      'documents.view',
      'documents.manage',
    ],
  },
  {
    name: 'Read Only',
    description: 'View-only access across the system.',
    isSystem: true,
    permissions: PERMISSION_KEYS.filter((k) => k.endsWith('.view')),
  },
];
